model:
  class_name: model.encoder_decoder.DecoupledNVSEncoderDecoder
  image_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 3
  pose_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 6
  target_pose_tokenizer:
    image_size: 256
    patch_size: 8
    in_channels: 6
  camera_encoding:
    ray_encoding: plucker
    attention_encoding: none
    prope_freq_base: 100.0
    prope_freq_scale: 1.0
  transformer:
    d: 768
    d_head: 64
    encoder_n_layer: 12
    decoder_n_layer: 12
    n_latent_vectors: 3072
    decouple: true
    film: true
    film_scale_init: 1.0
  irepa:
    decoder_depth: 3
    dino_layer: 7
    feature_dim: 768
    image_size: 448
    interpolate_mode: bilinear
    weight_path: path_to_dinov3_weights/dinov3-vitb16-pretrain-lvd1689m.pth
    repo: facebookresearch/dinov3
training:
  amp_dtype: bf16
  api_key_path: ./configs/api_keys.yaml
  batch_size_per_gpu: 4
  beta1: 0.9
  beta2: 0.95
  allowed_gradnorm_factor: 5
  center_crop: true
  scene_scale_factor: 1.35
  checkpoint_every: 0
  eval_every: 0
  grad_accum_steps: 1
  grad_checkpoint_every: 1
  grad_clip_norm: 5.0
  scheduler_type: constant
  l2_loss_weight: 1.0
  lpips_loss_weight: 0.0
  dino: true
  dino_loss_weight: 0.5
  dino_gamma: 0.6
  spatial_layer: 9
  lr: 0.0004
  train_steps: 50000
  num_threads: 8
  num_workers: 8
  prefetch_factor: 4
  print_every: 20
  vis_every: 1000
  square_crop: true
  target_has_input: true
  use_amp: true
  use_rel_pose: false
  use_tf32: true
  wandb_log_every: 50
  wandb_project: SSD-LVSM
  weight_decay: 0.05
  checkpoint_dir: ./experiments/checkpoints/objaverse_encoder_decoder
  dataset_name: data.dataset_objaverse.Dataset
  dataset_path: path_to_objaverse/object-paths.json.gz
  excluded_scene_list: ./data/evaluation_objaverse_100_seed777.txt
  objaverse_root: path_to_objaverse
  objaverse_fovy_deg: 49.1
  perceptual_loss_weight: 1.0
  num_input_views: 4
  num_target_views: 8
  num_views: 12
  warmup: 2500
  view_window_frames: 16
  view_selector:
    max_frame_dist: 23
    min_frame_dist: 2
  wandb_exp_name: objaverse_encoder_decoder
  spatial_correspondence_loss_weight: 0.5
  spatial_correspondence_min_valid: 50
  spatial_supervision: true
  depth_camera_cache_root: path_to_depth_camera_cache/objaverse
inference:
  if_inference: false
  compute_metrics: false
  view_idx_file_path: ./data/evaluation_index_objaverse_100_seed777.json
  render_video: false
  render_video_config:
    traj_type: interpolate
    num_frames: 60
    loop_video: true
    order_poses: false
  test_dataset_path: ./data/evaluation_objaverse_100_seed777.txt
  test_objaverse_root: path_to_objaverse
